Patch the workflow that has been fixed already on master
Copies the fix by @andreasabel

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,7 +22,10 @@ env:
   STDLIB_VERSION: '2.3'
   DEPLOY_DIR: ${{ github.ref_name }}
   HTML_DIR: html/${{ github.ref_name }}
+  # Entry point for Agda compilation
   MAIN: Everything.agda
+  # Entry point for uploaded HTML, becomes index.html
+  INDEX: Everything.html
 
 jobs:
   build:
@@ -31,27 +34,88 @@ jobs:
     steps:
 
       # Checkout to $HOME empties $HOME so we have to do it before we put stuff there.
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
+
+      - name: Debug info --- directories
+        run: |
+          echo "HOME = ${HOME}"
+          echo "current directory = $(pwd)"
+
+      - name: Download Agda ${{ env.AGDA_VERSION }}
+        run: |
+          http_code=$(curl -w '%{http_code}\n' -L "https://github.com/agda/agda/releases/download/v${{ env.AGDA_VERSION }}/Agda-v${{ env.AGDA_VERSION }}-linux.tar.xz" -o "agda.tar.xz")
+          exit_code=$?
+          echo "curl exit code: ${exit_code}"
+          echo "curl http code: ${http_code}"
+          if [[ "${exit_code}" == "0" && "${http_code}" == "200" ]]; then
+            tar xvf agda.tar.xz
+            mkdir -p "${HOME}/.local/bin/"
+            mv agda "${HOME}/.local/bin/"
+            echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"
+          else
+            echo "Download of Agda archive failed."
+            exit 1
+          fi
 
       - name: Setup Agda
-        uses: wenkokke/setup-agda@v2
-        id:   setup
-        with:
-          agda-version: ${{ env.AGDA_VERSION }}
-          agda-stdlib-version: ${{ env.STDLIB_VERSION }}
+        run: |
+          agda --setup
+          AGDA_DIR=$(agda --print-agda-app-dir)
+          mkdir -p "${AGDA_DIR}"
+          mkdir -p "${AGDA_DIR}/libraries.d"
+          echo "AGDA_DIR=${AGDA_DIR}" >> "${GITHUB_ENV}"
+
+      - name: Download Agda standard-library ${{ env.STDLIB_VERSION }}
+        run: |
+          http_code=$(curl -w '%{http_code}\n' -L "https://github.com/agda/agda-stdlib/archive/refs/tags/v${{ env.STDLIB_VERSION }}.tar.gz" -o "agda-stdlib.tgz")
+          exit_code=$?
+          echo "curl exit code: ${exit_code}"
+          echo "curl http code: ${http_code}"
+          if [[ "${exit_code}" == "0" && "${http_code}" == "200" ]]; then
+            tar xvf agda-stdlib.tgz -C "${AGDA_DIR}/libraries.d/"
+            ls -al
+          else
+            echo "Download of the Agda standard library archive failed."
+            exit 1
+          fi
+
+      - name: Setup Agda standard-library
+        run: |
+          echo "${AGDA_DIR}/libraries.d/agda-stdlib-${{ env.STDLIB_VERSION }}/standard-library.agda-lib" >> "${AGDA_DIR}/libraries"
+          cat "${AGDA_DIR}/libraries"
+          ls -al "${AGDA_DIR}/libraries.d/agda-stdlib-${{ env.STDLIB_VERSION }}/standard-library.agda-lib"
 
       - name: Restore cache
         uses: actions/cache/restore@v4
         id:   cache
         with:
-          key: agda-${{ steps.setup.outputs.agda-version }}-stdlib-${{ env.STDLIB_VERSION }}-commit-${{ github.sha }}
-          restore-keys: agda-${{ steps.setup.outputs.agda-version }}-stdlib-${{ env.STDLIB_VERSION }}-
+          key: agda-${{ env.AGDA_VERSION }}-stdlib-${{ env.STDLIB_VERSION }}-commit-${{ github.sha }}
+          restore-keys: agda-${{ env.AGDA_VERSION }}-stdlib-${{ env.STDLIB_VERSION }}-
           path: |
             _build
-            ~/.agda/libraries.d
+            ${{ env.AGDA_DIR }}/libraries.d
+
+      # setup-agda does not support 2.8.0
+
+      # - name: Setup Agda
+      #   uses: wenkokke/setup-agda@v2
+      #   id:   setup
+      #   with:
+      #     agda-version: ${{ env.AGDA_VERSION }}
+      #     agda-stdlib-version: ${{ env.STDLIB_VERSION }}
+
+      # - name: Restore cache
+      #   uses: actions/cache/restore@v4
+      #   id:   cache
+      #   with:
+      #     key: agda-${{ steps.setup.outputs.agda-version }}-stdlib-${{ env.STDLIB_VERSION }}-commit-${{ github.sha }}
+      #     restore-keys: agda-${{ steps.setup.outputs.agda-version }}-stdlib-${{ env.STDLIB_VERSION }}-
+      #     path: |
+      #       _build
+      #       ~/.agda/libraries.d
 
       - name: Run Agda
-        run: agda "${{ env.MAIN }}" +RTS -M6G -RTS
+        run: agda "${{ env.MAIN }}"
 
       - name: Save cache
         # Primary cache key is unique, so we can always save.
@@ -61,23 +125,27 @@ jobs:
           key: ${{ steps.cache.outputs.cache-primary-key }}
           path: |
             _build
-            ~/.agda/libraries.d
+            ${{ env.AGDA_DIR }}/libraries.d
 
 ########################################################################
 ## DOC DEPLOYMENT
 ########################################################################
 
-      # We start by retrieving the currently deployed docs
+      # We start by retrieving the currently deployed docs.
       # We remove the content that is in the directory we are going to populate
       # so that stale files corresponding to deleted modules do not accumulate.
-      # We then generate the docs in the HTML_DIR subdirectory
-      - name: Generate HTML
+
+      - name: Checkout branch gh-pages to html
         run: |
           git clone --depth 1 --single-branch --branch gh-pages https://github.com/graded-type-theory/graded-type-theory.git html
           rm -f '${{ env.HTML_DIR }}'/*.html
           rm -f '${{ env.HTML_DIR }}'/*.css
+
+      # We then generate the docs in the HTML_DIR subdirectory.
+      - name: Generate HTML
+        run: |
           agda --html --html-dir="${{ env.HTML_DIR }}" "${{ env.MAIN }}"
-          cp "${{ env.HTML_DIR }}/README.html" "${{ env.HTML_DIR }}/index.html"
+          cp "${{ env.HTML_DIR }}/${{ env.INDEX }}" "${{ env.HTML_DIR }}/index.html"
 
       - name: Deploy HTML
         uses: JamesIves/github-pages-deploy-action@v4
@@ -88,6 +156,6 @@ jobs:
           folder: html
           git-config-name: Github Actions
 
-      - uses: actions/upload-pages-artifact@v3
+      - uses: actions/upload-pages-artifact@v4
         with:
           path: html
